ALTER TYPE "FindingType" ADD VALUE IF NOT EXISTS 'EXTERNAL_LINK_SIGNAL';
ALTER TYPE "FindingType" ADD VALUE IF NOT EXISTS 'AD_PERSUASION_SIGNAL';
ALTER TYPE "FindingType" ADD VALUE IF NOT EXISTS 'PRIVACY_CONCERN';
ALTER TYPE "FindingType" ADD VALUE IF NOT EXISTS 'SOURCE_CONTEXT_SIGNAL';
